Delete .circleci directory
gorilla/feeds pull request #100
Opened 2023-07-19 20:16 UTC by coreydaley

Fixes #

**Summary of Changes**

1.
2. 
3.

> PS: Make sure your PR includes/updates tests! If you need help with this part, just ask!

2023-07-25 16:42 UTC, apoorvajagtap commented on README.md
How about adding the logo as well?

```
![Gorilla Logo](https://cloud-cdn.questionable.services/gorilla-icon-64.png)
```

2023-07-25 17:32 UTC, apoorvajagtap approved these changes

2023-07-25 17:34 UTC, apoorvajagtap requested changes
@coreydaley should we delete the AUTHORS file for this one as well?

2023-07-25 19:41 UTC, coreydaley commented
@apoorvajagtap good catch, updated in current push

2023-07-26 07:02 UTC, apoorvajagtap approved these changes

2023-07-26 07:03 UTC, merged